version: '3.8'

# Offizielles Docker-Image für InfluxDB: https://hub.docker.com/_/influxdb

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=mein-influxdb-nutzer
      - DOCKER_INFLUXDB_INIT_PASSWORD=mein-super-geheimes-passwort
      - DOCKER_INFLUXDB_INIT_ORG=reminder-org
      - DOCKER_INFLUXDB_INIT_BUCKET=reminder-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mein-super-geheimes-auth-token
